SolarAfrica Platform/SovTech/NVIDev/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NVIDev.ActionFilters;
using NVIDev.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Data.Entity.SqlServer;
using Newtonsoft.Json;
using System.Data.SqlClient;
using System.IO;

namespace NVIDev.Controllers
{
    //[Authorize(Roles = "NVIAdmin, TPAdmin")]
    //[CustAuthFilter]
    public class DocumentController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        DBHelper dbHelper = new DBHelper();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Document
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [Authorize(Roles = "NVIAdmin, TPAdmin")]
        public ActionResult ApprovedDocument()
        {
            var Users = db.ApprovalDocument.ToList();
            IEnumerable<ApprovalDocument> oList = (IEnumerable<ApprovalDocument>)Users;

            List<Vw_User> UserList = db.Database.SqlQuery<Vw_User>("SELECT  [UserId],[Email],[PasswordHash],[PhoneNumber],[UserName],[Company],[Image],[Road],[City],[Country],[Salutation],[FirstName],[LastName],[UserType],[Designation],[CreatedOn],[RoleId],[RoleName]  FROM  [Vw_Users]  Where [RoleName]!= 'NVIAdmin' ").ToList();
            var raw = UserList.Select(x => new SelectListItem { Text = x.FirstName + " " + x.LastName, Value = x.UserId }).ToList();
            ViewBag.UserList = raw;

            var rawCompany = db.Company.Select(x => new SelectListItem { Value = x.CompanyID.ToString(), Text = x.CompanyName }).ToList();
            ViewBag.CompanyList = rawCompany;

            return View(oList);

        }

        /// <summary>
        /// Bind Method for Binding Approved Document
        /// </summary>
        /// <returns></returns>
        public ApprovalDocumentModelLayer ApprovedDocumentMethod()
        {
            ApprovalDocumentModelLayer oApprovalDocument = new ApprovalDocumentModelLayer();

            var Users = db.ApprovalDocument.ToList();
            //ViewBag.List = db.Users.Join(db.Roles, a => a.Id, b => b.Id, (a, b) => new SelectListItem { Text = a.FirstName, Value = a.Id }).ToList();

            //List<Vw_User> UserList = db.Database.SqlQuery<Vw_User>("SELECT  [UserId],[Email],[PasswordHash],[PhoneNumber],[UserName],[Company],[Image],[Road],[City],[Country],[Salutation],[FirstName],[LastName],[UserType],[Designation],[CreatedOn],[RoleId],[RoleName]  FROM  [Vw_Users]  Where [RoleName]!= 'NVIAdmin' ").ToList();
            var raw = dbHelper.GetUserList().Select(x => new SelectListItem { Text = x.FirstName + " " + x.LastName, Value = x.UserId }).ToList();
            ViewBag.UserList = raw;

            var rawCompany = db.Company.Select(x => new SelectListItem { Value = x.CompanyID.ToString(), Text = x.CompanyName }).ToList();
            ViewBag.CompanyList = rawCompany;


            //ViewBag.UserList = db.Roles.Select(x => x.Users.Select(y => new { y.UserId, y.RoleId })
            //    .Join(db.Users, a => a.UserId, b => b.Id, (a, b) => new SelectListItem { Text = b.FirstName + " " + b.LastName, Value = b.Id }).ToList());

            //ViewBag.UserList = db.Users.Join(db.Roles.Where(y => y.Name != "NVIAdmin").Select(x => x.Users), a => a.Id, b => b.Select(g => g.UserId), (a, b) =>
            //    new SelectListItem { Text = a.FirstName + " " + a.LastName, Value = a.Id }).OrderBy(x => x.Text).ToList();

            //ViewBag.UserList = db.Users.Where(x => x.RoleID != 1)
            //    .Select(x => new SelectListItem { Text = x.FirstName + " " + x.LastName, Value = x.UserID.ToString() }).OrderBy(x => x.Text).ToList();

            oApprovalDocument.AdminApprovalDocumentList = (IEnumerable<ApprovalDocument>)Users;
            return oApprovalDocument;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        /// 
        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "NVIAdmin, TPAdmin")]
        public ActionResult ApprovedDocument(ApprovalDocumentModelLayer oApprovalDocument)
        {
            if (ModelState.IsValid)
            {
                ApprovalDocument nApprovalDocument = new ApprovalDocument();
                nApprovalDocument.ApprovalDocumentId = oApprovalDocument.AdminApprovalDocument.ApprovalDocumentId;
                nApprovalDocument.ApprovalDocumentMenu = "";// oApprovalDocument.AdminApprovalDocument.ApprovalDocumentMenu;
                nApprovalDocument.ApprovalDocumentSubMenu = oApprovalDocument.AdminApprovalDocument.ApprovalDocumentSubMenu;
                nApprovalDocument.IsActive = true;
                nApprovalDocument.CreatedBy = User.Identity.GetUserId();
                nApprovalDocument.CreatedOn = DateTime.Now;
                db.ApprovalDocument.Add(nApprovalDocument);
                db.SaveChanges();

                ModelState.AddModelError("AdminApprovalDocument.TriggerOnLoadMessage", "Record save successfully.");

                oApprovalDocument.AdminApprovalDocument.ApprovalDocumentMenu = string.Empty;
                oApprovalDocument.AdminApprovalDocument.ApprovalDocumentSubMenu = string.Empty;
                oApprovalDocument.AdminApprovalDocument.TriggerOnLoadMessage = "Record save successfully.";
                //ViewBag["SuccessMessage"] = "Record save successfully.";
            }

            oApprovalDocument = ApprovedDocumentMethod();
            return View(oApprovalDocument);
        }

        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize(Roles = "NVIAdmin, TPAdmin")]
        public ActionResult AddDocument()
        {
            ApprovalDocumentModel oApprovalDocument = new ApprovalDocumentModel();
            oApprovalDocument.ApprovalDocumentMenu = string.Empty;
            //bind dropdown from database for country list
            List<SelectListItem> list = new List<SelectListItem>();
           // list.Add(new SelectListItem { Text = "-Please select-", Value = "Selects items" });
            var cat = (from c in db.Countries select c).ToArray();
            for (int i = 0; i < cat.Length; i++)
            {
                list.Add(new SelectListItem
                {
                    Text = cat[i].Id,
                    Value = cat[i].Id.ToString()
                });
            }
            ViewData["Countries"] = list;
            //bind organisation dropdown from database
            List<SelectListItem> listOrg = new List<SelectListItem>();
          //  listOrg.Add(new SelectListItem { Text = "-Please select-", Value = "Selects items" });
            var org = (from c in db.Company select c).ToArray();
            for (int i = 0; i < org.Length; i++)
            {
                listOrg.Add(new SelectListItem
                {
                    Text = org[i].CompanyName,
                    Value = org[i].CompanyID.ToString()
                });
            }
            ViewData["Organisation"] = listOrg;
            return PartialView(oApprovalDocument);
        }

        [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "NVIAdmin, TPAdmin")]
        public JsonResult AddDocument(ApprovalDocumentModel oApprovalDocument)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    ApprovalDocument nApprovalDocument = new ApprovalDocument();
                    nApprovalDocument.ApprovalDocumentId = oApprovalDocument.ApprovalDocumentId;
                    nApprovalDocument.ApprovalDocumentMenu =  oApprovalDocument.ApprovalDocumentMenu;
                    nApprovalDocument.ApprovalDocumentSubMenu = oApprovalDocument.ApprovalDocumentSubMenu;
                    nApprovalDocument.ApprovalDocumentDesc = oApprovalDocument.ApprovalDocumentDesc;
                    if(oApprovalDocument.ApprovalDocumentMenu.ToString() == "Country Specific")
                    nApprovalDocument.CounOrgSpecificName = oApprovalDocument.CounSpecificName;
                    else
                        nApprovalDocument.CounOrgSpecificName = oApprovalDocument.OrgSpecificName;
                    nApprovalDocument.IsActive = true;
                    nApprovalDocument.CreatedBy = User.Identity.GetUserId();
                    nApprovalDocument.CreatedOn = DateTime.Now;
                    db.ApprovalDocument.Add(nApprovalDocument);
                    db.SaveChanges();
                    return Json("Success");
                }
                catch (Exception ex)
                {
                    return Json(ex.Message);
                }
            }
            return Json("Fail");
        }


        /// <summary>
        /// Show All TP User Information
        /// </summary>
        /// <param name="column"></param>
        /// <param name="sidx"></param>
        /// <param name="sord"></param>
        /// <param name="page"></param>
        /// <param name="rows"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public JsonResult TPUserList(string column, string sidx = "UserID", string sord = "asc", int page = 1, int rows = 50) // Gets the list of Labours
        {
            int pageIndex = Convert.ToInt16(page) - 1;
            int pageSize = rows;
            var LabourList1 = (dynamic)null;
            var totalRecords = (dynamic)null;

SolarAfrica Platform/SovTech/NVIDev/Views/Document/AddDocument.cshtml
@model NVIDev.Models.ApprovalDocumentModel


@using (Ajax.BeginForm("AddDocument", new AjaxOptions { HttpMethod = "POST", OnSuccess = "successCurrency" }))
{
    @Html.AntiForgeryToken()
    <script type="text/javascript">
    function hideAccAdmReg(idhide, idShow) {
        document.getElementById(idhide).style.display = "none";
        document.getElementById(idShow).style.display = "block";
    }

    </script>
    <div id="Document-form" class="Currency">
        <div class="form-horizontal">
            <h4>Add Document</h4>
            <hr />

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.ApprovalDocumentId, new { id = "ApprovalDocumentId", @Value = "0" })
            @Html.LabelFor(model => model.TriggerOnLoadMessage)
            @Html.ValidationMessageFor(model => model.TriggerOnLoadMessage)

            <div id="myMessage1" class="text-danger"></div>
            
            <div class="raw"> 
                <div class="form-group">
                    @Html.LabelFor(model => model.ApprovalDocumentMenu, htmlAttributes: new { @class = "control-label  col-md-4 reqfield" })
                    @Html.RadioButtonFor(model => model.ApprovalDocumentMenu, "Country Specific", new { id = "CountrySpecific", @checked = "checked", onchange = "hideAccAdmReg('divOrganisationSpecific','divCountrySpecific');" })
                    @Html.Label("CountrySpecific", "Country Specific")

                    @Html.RadioButtonFor(model => model.ApprovalDocumentMenu, "Organisation Specific", new { id = "OrganisationSpecific", onchange = "hideAccAdmReg('divCountrySpecific','divOrganisationSpecific');" })
                    @Html.Label("OrganisationSpecific", "Organisation Specific")                                    
                </div>
                <div class="form-group" id="divCountrySpecific">
                    @Html.LabelFor(model => model.CounSpecificName, htmlAttributes: new { @class = "control-label  col-md-4 reqfield" })
                    @Html.DropDownListFor(m => m.CounSpecificName, (IEnumerable<SelectListItem>)ViewData["Countries"], new { id = "ddlCountryID", @class = "form-control" })                  
                    @Html.ValidationMessageFor(model => model.CounSpecificName)
                </div>
                <div class="form-group" style="display:none;" id="divOrganisationSpecific">
                    @Html.LabelFor(model => model.OrgSpecificName, htmlAttributes: new { @class = "control-label  col-md-4 reqfield" })
                    @Html.DropDownListFor(m => m.OrgSpecificName, (IEnumerable<SelectListItem>)ViewData["Organisation"], new { id = "ddlOrganisationID", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OrgSpecificName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ApprovalDocumentSubMenu, htmlAttributes: new { @class = "control-label col-md-4 reqfield" })
                    @Html.EditorFor(model => model.ApprovalDocumentSubMenu, new { htmlAttributes = new { @class = "form-control col-md-7", @title = "Enter Document Menu Name" } })
                    @Html.ValidationMessageFor(model => model.ApprovalDocumentSubMenu)
                </div>
                <div class="form-group  ">
                    @Html.LabelFor(model => model.ApprovalDocumentDesc, htmlAttributes: new { @class = "control-label col-md-4 reqfield" })
                    @Html.TextAreaFor(model => model.ApprovalDocumentDesc, new { htmlAttributes = new { @class = "form-control col-md-7", @title = "Enter Document Description" } })
                    @Html.ValidationMessageFor(model => model.ApprovalDocumentDesc)
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <input type="button" value="Cancel" class="btn btn-warning" onclick="HideDocument()" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")



}

SolarAfrica Platform/SovTech/NVIDev/Views/Document/ApprovalDocument.cshtml
@model NVIDev.Models.AttachDocModel
@{
    ViewBag.Title = "Approval Document";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var count = 0;
}

@*Very Important Note
This page contains some element with title please dont change its title name because they are used as JQuery selectors*@

<style>
    .td-aligncenter {
    text-align:center
    }
</style>

<div class="ibox-title">
    <h2>Approval Document</h2>
</div>

@using (Html.BeginForm("ApprovalDocument", "Document", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="ibox-content">
    <table class="table table-bordered table-hover" id="tblApprovaldocument">
        <tr>
            <th>

            </th>
            <th>
                Document Type
            </th>
            <th>
                Document Name
            </th>
            <th>
                View
            </th>
            <th>
                Status
            </th>
            <th>
                Action
            </th>
        </tr>
        @*@foreach (var item in Model)
            {*@
        @foreach (var item in (List<NVIDev.Models.AttachDocModel>)ViewBag.DocDetails)
        {            
            <tr>
                <td>
                    <input type="hidden" value="@item.CompanyID" id="hdnCompanyid" />                    
                    @*<input type="checkbox" checked="@item.IsActive" disabled="disabled" />*@
                    @{
            count = count + 1;
                    }
                    @count
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApprovalDocumentMenu)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ApprovalDocumentSubMenu)
                </td>
                <td>
                    @{
                if (item.AttachedFile != null)
                {
                    <input type="submit" value="View" class="btn btn-default btn-sm" id="btnDwnload_@item.ApprovalDocumentId" onclick="return adddocidinhdnfield(this.id);">
                    <a class="btn btn-primary btn-xs">@item.Attachedfilename</a>                
                }
                    }
                </td>
                @if (item.IsApproved == null)
                {
                    <td>
                        <label id="lblStatus">No Attachment Found</label>
                    </td>
                    <td class="td-aligncenter">
                        <a id="btncomment_@item.ApprovalDocumentId" onclick="return adddocidinhdnfield(this.id);" title="Add Comments"><span class="glyphicon glyphicon-comment"></span></a>
                        |<a id="btnviewcomment_@item.ApprovalDocumentId" onclick="return ShowAllComments(this.id);" title="View All Comments"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                }
                else if (item.IsApproved == "0")
                {
                    <td>
                        <label id="lblStatus">Pending for approval</label>
                    </td>
                    <td class="td-aligncenter">
                        <a id="btnapprove_@item.ApprovalDocumentId" onclick="adddocidinhdnfield(this.id);" title="Approve"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                        |<a id="btnreject_@item.ApprovalDocumentId" onclick="adddocidinhdnfield(this.id);" title="Approve"><span class="glyphicon glyphicon-thumbs-down"></span></a>
                        @*<input type="button" value="Approved" title="approve" id="btnapprove_@item.ApprovalDocumentId" onclick="adddocidinhdnfield(this.id)" class="btn btn-success btn-sm">
                        <input type="button" value="Reject" id="btnreject_@item.ApprovalDocumentId" onclick="adddocidinhdnfield(this.id)" class="btn btn-primary btn-sm">*@
                        |<a id="btncomment_@item.ApprovalDocumentId" onclick="return adddocidinhdnfield(this.id);" title="Add Comments"><span class="glyphicon glyphicon-comment"></span></a>
                        |<a id="btnviewcomment_@item.ApprovalDocumentId" onclick="return ShowAllComments(this.id);" title="View All Comments"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                }
                else if (item.IsApproved == "2")
                {
                    <td>
                        <label id="lblStatus">Rejected</label>
                    </td>
                    <td class="td-aligncenter">
                        <a id="btncomment_@item.ApprovalDocumentId" onclick="return adddocidinhdnfield(this.id);" title="Add Comments"><span class="glyphicon glyphicon-comment"></span></a>
                        |<a id="btnviewcomment_@item.ApprovalDocumentId" onclick="return ShowAllComments(this.id);" title="View All Comments"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                }
                else
                {
                    <td>
                        <label id="lblStatus">Approved</label>
                    </td>
                    <td class="td-aligncenter">
                        <a id="btncomment_@item.ApprovalDocumentId" onclick="return adddocidinhdnfield(this.id);" title="Add Comments"><span class="glyphicon glyphicon-comment"></span></a>
                        |<a id="btnviewcomment_@item.ApprovalDocumentId" onclick="return ShowAllComments(this.id);" title="View All Comments"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                }
            </tr>
        }
    </table>
    <div id="divQtipComment" style="display: none">
      <p>
          <textarea rows="2" name="txtComment" id="txtComment" cols="30" onkeyup="setAdminComments(this)"></textarea>
      </p>
        <p>
            <input type="button" value=">>" id="btnsavecoments" class="btn btn-primary btn-sm" onclick="AddCommentForDocument(); HideQtip(this);">
        </p>          
    </div>

    <div id="divQtipDocApproval" style="display: none">
        <p>
            <span>Comments:</span>
            <textarea rows="2" name="txtComment" id="txtComment" cols="35" onkeyup="setAdminComments(this)"></textarea>
        </p>
        <p>
            <input type="button" value="Yes" class="btn btn-primary btn-sm" onclick="Approverejectdoc();">
        </p>
    </div>

        @Html.HiddenFor(model => model.ApprovalDocumentId, new { @id = "hdnApprovalDocumentId" })
    <input type="hidden" id="hdnAdminComments" />  
    <input type="hidden" id="hdnApprovalType" /> 
    </div>
}
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Content/plugins/Qtip/jquery.qtip.min.css" rel="stylesheet" />
<script src="~/Content/plugins/Qtip/jquery.qtip.min.js"></script>

    <script type="text/javascript">
        var $j = jQuery.noConflict();

        var user = sessionStorage["TPSn"];
        console.log(user)

        ///Added for Approval or Rejection 
        function Approverejectdoc() {
            try {
                $('#loading').show();

                AddCommentForDocument();

                var apprtype = document.getElementById('hdnApprovalType').value;
                var compnyid = document.getElementById('hdnCompanyid').value;
                var docid = document.getElementById('hdnApprovalDocumentId').value;

                var isapproved = apprtype == "btnapprove" ? "1" : "2";

                $.ajax({
                    url: oApp + "/Document/ApproveRejectDocument",
                    dataType: "json",
                    mtype: 'POST',
                    type: 'POST',
                    data: { 'companyid': compnyid, 'docid': docid, 'isapproved': isapproved },
                    success: function (result) {
                        $('#loading').hide();
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        if (xhr && thrownError) {
                            alert('Status: ' + xhr.status + ' Error: ' + thrownError);
                        }
                        $('#loading').hide();
                    }
                });
            }
            catch (ex) {
                console.log(ex);
            }
        }

        ///Added to set document id in hidden field
        function adddocidinhdnfield(id) {
            try {
                var docid = [];
                docid = id.split('_')
                document.getElementById('hdnApprovalDocumentId').value = docid[1];
                return true;
            }
            catch (ex) {
                console.log(ex);
                return false;
            }
        }

        var myApprovalContent = jQuery('#divQtipDocApproval').html();
        jQuery("[title*='Approve']").qtip({
            content: {
                text: myApprovalContent,
                title: function (event, api) {
                    var sender = [];
                    sender = (api.target[0].id).split('_')
                    if (sender[0] == "btnapprove") {
                        return "Are you sure, you want to approve this?";
                    }
                    else
                    {
                        return "Are you sure, you want to reject this?";
                    }
                }
            },
            events: {
                show: function (event, api) {
                    //console.log(event);
                    //console.log(api.target[0].id);
                    var docid = [];
                    docid = (api.target[0].id).split('_')
                    document.getElementById('hdnApprovalDocumentId').value = docid[1];
                    document.getElementById('hdnApprovalType').value = docid[0];
                }
            },
            hide: 'unfocus',
            show: {
                event: 'click',
                delay: 100,
                solo: true,
                ready: false
            },
            position: {
                my: 'top right',  // Position my top left...
                at: 'bottom right' // at the bottom right of...
            },
            style: {
                classes: 'qtip-light',
                width: 1000
            }
        })

        function setAdminComments(sender) {
            var currentID = sender.parentNode;
            //.parentNode.parentNode.parentNode.parentNode.parentNode;
            //console.log(sender);
            //console.log(currentID);
            //console.log($(currentID).find('textarea[id=txtComment]'));
            console.log($(currentID).find('textarea[id=txtComment]').val())
            document.getElementById('hdnAdminComments').value = $(currentID).find('textarea[id=txtComment]').val();
        }

        function AddCommentForDocument()
        {           
            $('#loading').show();
            var compnyid = document.getElementById('hdnCompanyid').value;
            var docid = document.getElementById('hdnApprovalDocumentId').value;
            var comment = document.getElementById('hdnAdminComments').value;
            if (comment != "") {
                $.ajax({
                    url: oApp + "/Document/AddCommentsForDocument",
                    dataType: "json",
                    mtype: 'POST',
                    type: 'POST',
                    data: { 'companyid': compnyid, 'docid': docid, 'comment': comment, 'commentType': "Admin" },
                    success: function (result) {
                        $('#loading').hide();
                        //window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        if (xhr && thrownError) {
                            alert('Status: ' + xhr.status + ' Error: ' + thrownError);
                        }                        
                    }
                });
            }
            $('#loading').hide();
        }

        function ShowAllComments(btnid) {
            var docid = [];
            docid = btnid.split('_')
            var docid = docid[1];
            var compnyid = document.getElementById('hdnCompanyid').value;            
            $.fancybox({
                'autoScale': true,
                'type': 'iframe',
                'width': 800,
                'height': 400,
                overlayOpacity: '0.8',
                href: oApp + '/Document/ShowAllComments?docid=' + docid + '&companyid=' + compnyid,
                'onCleanup': function () {
                    try {

                    } catch (err) {
                        console.log(err);
                    }
                }
            });
        }

        ///Added to add comments
        var myContent = jQuery('#divQtipComment').html();
        jQuery("[title*='Add Comments']").qtip({
            content: {
                text: myContent,
                title: {
                    text: 'Add Comments',
                    button: true
                }
            },
            hide: 'unfocus',
            show: {
                event: 'click',
                delay: 100,
                solo: true,
                ready: false
            },
            position: {
                my: 'top right',  // Position my top left...
                at: 'bottom right' // at the bottom right of...
            },
            style: {
                classes: 'qtip-light',
                width: 1000
            }
            //events: {
            //    render: function (event, api) {
            //        alert('dfd');
            //    }
            //}
        })

        function HideQtip(sender)
        {
            var qtipdiv = sender.parentNode.parentNode.parentNode;
            $(qtipdiv).hide();
        }
    </script>

SolarAfrica Platform/SovTech/NVIDev/Views/Document/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
} 


@section Submenu{

    @Html.Partial("_AdminNav")

}

<div class="ibox-title">
    <h2>TP INFORMATION</h2>

    <table id="grdUser"></table>
    <table id="grdPager"></table>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqGrid")
    @Scripts.Render("~/bundles/Admin")

SolarAfrica Platform/SovTech/NVIDev/Views/Document/PopupUploadDoc.cshtml
@model NVIDev.Models.AttachDocModel

@{
    ViewBag.Title = "Company Detail";
    Layout = "~/Views/Shared/_PartialView.cshtml";
}

<h2>Attachments</h2>

@using (Html.BeginForm("PopupUploadDoc", "Document", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="ibox-content">
    <table>
        <tr>
            <td>@Html.TextBoxFor(model => model.AttachmentName, new { @id = "fuAttachment", type = "file", @class = "form-control", @accept = ".jpg,.jpeg,.gif,.png,.bmp,.PNG,.JPG,.JPEG,.GIF,.BMP,.xls,.xlsx,.pdf,.docx,.txt" })</td>
            <td><input type="submit" class="btn btn-success" value="Attach" id="btnUpload" /></td>
        </tr>
    </table>
</div>
}

SolarAfrica Platform/SovTech/NVIDev/Views/Document/ShowAllComments.cshtml
@model NVIDev.Models.AttachDocModel

@{
    ViewBag.Title = "Company Detail";
    Layout = "~/Views/Shared/_PartialView.cshtml";
}

<h2>Comments</h2>

<div class="ibox-content">

    <table class="table table-bordered table-hover" id="tblApprovaldocument">
    <tr>
        <th>
            Admin Comments
        </th>
        <th>
            TP-User Comments 
        </th>
    </tr>
@foreach (var item in (List<NVIDev.Models.AttachDocModel>)ViewBag.DocDetails)
{
    string[] admincomments = new string[0];
    string[] tpcomments = new string[0];
    if (!string.IsNullOrEmpty(item.AdminComment))
    {
        admincomments = item.AdminComment.Split(';');
    }
    if (!string.IsNullOrEmpty(item.TPUserComment))
    {
        tpcomments = item.TPUserComment.Split(';');
    }
        <tr>
            <td>
                <table>
                    @foreach (string adcom in admincomments) 
                    {
                    <tr>
                        <td>
                            @adcom
                        </td>
                    </tr>
                    }
                </table>
            </td>
            <td>
                <table>
                    @foreach (string tpcom in tpcomments)
                    {
                    <tr>
                        <td>
                            @tpcom
                        </td>
                    </tr>
                    }
                </table>
            </td>
        </tr>
}
    </table>

</div>