SolarAfrica Platform/SovTech/NVIDev/Models/Audit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NVIDev.Models
{
    public class Audit
    {
        [Key]
        public long Id {get;set;}
        public string UserID { get; set; }
        public string Company { get; set; }

        public string Content { get; set; }
        public DateTime Time { get; set; }
        public Audit ()
        {
            Time = DateTime.Now;
        }


        public Audit(string userID, string company, string content)
        {
            UserID = userID;
            Content = content;
            Time = DateTime.Now;
            Company = company;
        }

        public Audit(Audit other)
        {
            Id = other.Id;
            UserID = other.UserID;
            Content = other.Content;
            Time = other.Time;
            Company = other.Company;
        }

       
    }
}

SolarAfrica Platform/SovTech/NVIDev/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NVIDev.Models;
using System.Data.Entity.Validation;
using System.Diagnostics;
using iTextSharp.text;
using iTextSharp.text.pdf;
using MvcRazorToPdf;
using System.Web.Helpers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.IO;
using Excel;
using NVIDev.ActionFilters;




namespace NVIDev.Controllers
{
    [Authorize(Roles = "NVIAdmin,NVIUser,TPAdmin,TPUser")]
    [CustAuthFilter]
    public class ProjectController : Controller
    {

        private DBHelper dbhelper = new DBHelper();
        public ActionResult Index()
        {
            var currentUserID = User.Identity.GetUserId();

            List<Project> myProjects = dbhelper.GetUserProjects(currentUserID);

            foreach (var project in myProjects)
            {
                project.isEnergyDone();
            }
            return View(myProjects);
        }

        public ActionResult Test(int id)
        {
            var project = dbhelper.GetProject(id);
            SuperProject model = new SuperProject(project);
            return View(model);
        }

        public ActionResult Test2(int id)
        {
            var project = dbhelper.GetProject(id);
            SuperProject model = new SuperProject(project);
            return View(model);
        }


        #region Project Core
        public ActionResult Details(int id)
        {

            Project project = dbhelper.GetProject(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            if (User.Identity.GetUserId() == project.CurrentUserID || User.IsInRole("NVIAdmin"))
            {
                return View(project);

            }

            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
        }
        // GET: /Project/Create
        public ActionResult Create()
        {
            ViewBag.Titles = dbhelper.PersonTitles();
            ViewBag.Ports = dbhelper.GetAllPortNames();
            ViewBag.Countries = dbhelper.GetAllCountryNames();

            Project model = new Project();
            return View(model);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Costing, CurrentUserID,CreatorID, Code, Id")]Project project)
        {

            if (ModelState.IsValid)
            {


                bool Success = dbhelper.CreateProject(project, User.Identity.GetUserId());

                if (Success)
                {
                    AddAudit(User.Identity.GetUserId(), string.Format("{0} Created a new project : {1}.", CurrentUsername(), project.Details.ProjectName));

                    return RedirectToAction("EditCosting", new { @id = project.Id });
                }

            }
            ViewBag.Titles = dbhelper.PersonTitles();
            ViewBag.Ports = dbhelper.GetAllPortNames();
            ViewBag.Countries = dbhelper.GetAllCountryNames();
            return View(project);
        }

        public ActionResult ShowMap()
        {

            return PartialView("~/Views/Project/_Map.cshtml");
        }


        public ActionResult Audits(int id)
        {
            List<Audit> projectsAudits = dbhelper.GetProjectAudits(id);
            return View(projectsAudits);
        }
        public ActionResult Maps()
        {
            return View();
        }
        public JsonResult GetPorts(string id)
        {
            List<string> ports = dbhelper.GetAllPortNames(id);
            List<string> gps = dbhelper.GetAllPorts(id).Select(m => m.GPS).ToList();
            if (ports == null || ports.Count <= 0)
            {
                ports.Add("NONE");
            }
            return Json(new[] { ports, gps });
        }

        // GET: /Project/Edit/5
        public ActionResult EditDetails(int id)
        {
            ViewBag.Titles = dbhelper.PersonTitles();
            ViewBag.Countries = dbhelper.GetAllCountryNames();
            ViewBag.Ports = dbhelper.GetAllPortNames();

            Project project = dbhelper.GetProject(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            if (project.CurrentUserID != User.Identity.GetUserId())
            {
                return RedirectToAction("Index");
            }


            return View(project);
        }

        // POST: /Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDetails([Bind(Exclude = "Costing,Code")]Project project)
        {
            if (ModelState.IsValid)
            {
                bool success = dbhelper.EditProjectDetails(project);

                if (success)
                {
                    AddAudit(User.Identity.GetUserId(), string.Format("{0} Edited  : {1} - Proposal Info.", CurrentUsername(), project.Details.ProjectName));
                    return RedirectToAction("EditDetails", new { Id = project.Id });
                }

            }

            ViewBag.Titles = dbhelper.PersonTitles();
            ViewBag.Countries = dbhelper.GetAllCountryNames();
            ViewBag.Ports = dbhelper.GetAllPortNames();

            return View(project);
        }



        public ActionResult EditCosting(int id)
        {
            ViewBag.Terms = dbhelper.Terms();
            ViewBag.Plans = dbhelper.ProjectPlans();
            ViewBag.Types = dbhelper.ProjectTypes();
            ViewBag.Sources = dbhelper.EnergySources();


            Project project = dbhelper.GetProject(id);
            ViewBag.Currency = dbhelper.GetCurrency(project.Details.P_Country);
            SuperProject summary = new SuperProject(project);
            ViewBag.Summary = new[] { summary.TFR.ToString("0.###"), summary.Up.ToString("0.##"), summary.prosize.ToString("0.##"), (summary.FP / 12.00).ToString("0.##") };


            if (project == null)
            {
                return HttpNotFound();
            }

            if (project.CurrentUserID != User.Identity.GetUserId())
            {
                //project is not assigned to current user
                return RedirectToAction("Index");
            }


            return View(project);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCosting([Bind(Exclude = "Details")]Project project)
        {
            if (ModelState.IsValid)
            {

                bool success = dbhelper.EditProjectCosting(project);

                if (success)
                {
                    Project a = dbhelper.GetProject(project.Id);
                    AddAudit(User.Identity.GetUserId(), string.Format("{0} Edited  : {1} - Energy Costs.", CurrentUsername(), a.Details.ProjectName));
                    return RedirectToAction("EditCosting", new { Id = project.Id });
                    //return Json(new[] { summary.TFR, summary.Up, summary.prosize, summary.FP / 12.00 });
                }

            }
            ViewBag.Terms = dbhelper.Terms();
            ViewBag.Plans = dbhelper.ProjectPlans();
            ViewBag.Types = dbhelper.ProjectTypes();
            ViewBag.Sources = dbhelper.EnergySources();
            return View(project);
        }





        [HttpGet]
        public ActionResult Quoting(int id)
        {

            Project project = dbhelper.GetProject(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            SuperProject super = new SuperProject(project);
            super.Project = super.PopulateCosts(super.Project);
            QuotingViewModel model = new QuotingViewModel();
            model.Populate(super);


            ViewBag.Currency = dbhelper.GetCurrency(project.Details.P_Country);
            ViewBag.Suppliers = dbhelper.Suppliers(User.Identity.GetUserId());

            if (project.CurrentUserID != User.Identity.GetUserId())
            {
                return RedirectToAction("Index");
            }


            return View(model);
        }



        [HttpPost]
        public ActionResult Quoting(QuotingViewModel model)
        {
            ViewBag.Suppliers = dbhelper.Suppliers(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {

                try
                {


                    bool Success = dbhelper.EditProjectQuoting(model);

                    Project a = dbhelper.GetProject(model.id);
                    ViewBag.Currency = dbhelper.GetCurrency(a.Details.P_Country);

                    if (Success)
                    {
                        AddAudit(User.Identity.GetUserId(), string.Format("{0} Edited  : {1} - Quoting.", CurrentUsername(), a.Details.ProjectName));
                        return RedirectToAction("Quoting", new { id = model.id });
                    }


                }

                catch
                {
                    return View(model);

                }
            }            

            return View(model);
        }


        public ActionResult AddCostLine(QuotingCost model)
        {
            model.Removeable = true;
            model.Assigned = true;
            model.Supplier = "NA";
            model.Main = false;
            model.WPMark = "Markup";
            model.UserID = User.Identity.GetUserId();
            model.CalculateSellPrice();
            string mess = dbhelper.TryInsertCostItem(model);
            return PartialView("~/Views/Project/_QuoteCost.cshtml", model);
        }


        public ActionResult ShowCostPartial()
        {

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/COOPort.cshtml
@model NVIDev.Models.Country2Port
@using (Html.BeginCollectionItem("Coo2Ports"))
{
    <tr>
        <td>@Model.Country @Html.HiddenFor(model => model.Country)</td>
        <td>
            <div class="input-group">
                @Html.HiddenFor(model => model.Amount20, new { @class = "form-control" }) @Html.ValidationMessageFor(model => model.Amount20) <span class="input-group-addon">$</span>
            </div>

        </td>
        <td>
            <div class="input-group">
                @Html.HiddenFor(model => model.Amount40, new { @class = "form-control" }) @Html.ValidationMessageFor(model => model.Amount40) <span class="input-group-addon">$</span>
            </div>
        </td>
    </tr>
}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/CreateBattery.cshtml
@model NVIDev.Models.Batteries

@{
    ViewBag.Title = "Create Battery";
}

@section Submenu{
    @Html.Partial("_AdminNav")


}

<div class="ibox-title">
    <h2>Create Battery</h2>
</div>


<div class="ibox-content">
    @using (Html.BeginForm())
    {

        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true)


            <div class="form-group">
                @Html.Label("Product Name", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Id, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Id)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Key", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Key, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Key)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Sub Category", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SubCategory, new SelectList(ViewBag.Subs), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SubCategory)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Manufacturer", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Manufacturer, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Manufacturer)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Lead Time", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.LeadTime, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LeadTime)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Description", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Dimensions", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Dimensions, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Dimensions)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Unit Of Measure", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UOM, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UOM)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Country Of Origin", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CountryOfOrigin, new SelectList(ViewBag.COO), new { @class = "form-control" }) @Ajax.ActionLink("Add Country +", "CreateCOO", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "AddCOO" })
                    @Html.ValidationMessageFor(model => model.CountryOfOrigin)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Currency", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CCY, new SelectList(ViewBag.Currencies), new { @class = "form-control" }) @Ajax.ActionLink("Add Currency +", "CreateCurrency", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "AddCurrency" })
                    @Html.ValidationMessageFor(model => model.CCY)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Unit Ah (C10)  ", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.UnitAh_C10, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UnitAh_C10)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Item Cost", new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.HiddenFor(model => model.ItemCost, new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.ItemCost)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Unit Cost/ Ah", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.UnitCost_WP, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UnitCost_WP)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Modules Per Pallet", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ModulesPerPallet, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ModulesPerPallet)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Pallets Per 20ft", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.PalletsPer20ft, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PalletsPer20ft)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Inco Terms", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.IncoTerms, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IncoTerms)
                </div>
            </div>









            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "EquipmentList")
    </div>

</div>
<div id="AddCOO"></div>
<div id="AddCurrency"></div>


@section Scripts {


    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/Scripts/coo.js")

@Scripts.Render("~/Scripts/Thousands.js")






}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/CreateCOO.cshtml
@model NVIDev.Models.CountryOfOrigin


@using (Ajax.BeginForm("CreateCOO", new AjaxOptions { HttpMethod = "POST", OnSuccess="successCOO" }))
{
    @Html.AntiForgeryToken()
    <div id="Coo-form" class="COO">


        <div class="form-horizontal">
            <h4>Country Of Origin</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div id="myMessage" class="text-danger"></div>
            <div class="form-group">
                @Html.Label("Country",  new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" /> <input type="button" value="Cancel" class="btn btn-warning" onclick="HideCOO()" />
                </div>
            </div>

        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/CreateCategory.cshtml
@model NVIDev.Models.CategoryViewModel

@{
    ViewBag.Title = "Create Category";
}

@section Submenu{
    @Html.Partial("_AdminNav")


}

<div class="ibox-title">
    <h2>Create Category</h2>
</div>

<div class="ibox-content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new {@class="form-control" } )
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Type, new SelectList(ViewBag.Types), new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <label class="col-md-2 control-label">Taxes  @Ajax.ActionLink("+", "AddTax", null, new AjaxOptions { HttpMethod = "GET", OnSuccess = "onSuccessAddCategory" }, new { @class = "btn btn-xs btn-primary" })</label>
            <table id="TaxTable" class="col-md-4 clearfix table-condensed">

                <tr>
                    <th>Name</th>
                    <th>Rate (%)</th>
                </tr>
            </table>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div>
    @Html.ActionLink("Back to List", "Categories")
</div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
@Scripts.Render("~/Scripts/Categories.js")
@Scripts.Render("~/Scripts/Deleter.js")





}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/CreateDuty.cshtml
@model NVIDev.Models.DutyViewModel

@{
    ViewBag.Title = "Create Duty";
}

@section Submenu{
    @Html.Partial("_AdminNav")
}

<div class="ibox-title">
    <h2>Create  Duty</h2>
</div>

<div class="ibox-content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.Label("Countries", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    <div class="duties-droplist form-control">
                        Select Countries
                        <ul class=" duties-droplist-list">
                            @{
        foreach (var country in Model.PossibleCountries)
        {

            @Html.Partial("UseCountry", country)

        }
                            }

                        </ul>
                    </div>

                </div>
                @Html.Label("Equipment", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    <div class="duties-droplist form-control">
                        Select Equipment
                        <ul class=" duties-droplist-list">
                            @{
        foreach (var item in Model.PossibleEquipment)
        {



            @Html.Partial("UseEquipment", item)

        }
                            }

                        </ul>
                    </div>

                </div>
                <div class="col-md-3"></div>
            </div>



            <div class="form-group">
                @Html.Label("All Countries", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <div>
                        @Html.CheckBoxFor(model => model.AllCountries, new { @class = "checkbox" })
                        @Html.ValidationMessageFor(model => model.AllCountries, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            @*<div class="form-group">
                        @Html.Label("Equipment", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="duties-droplist form-control">
                                Select Equipment
                                <ul class=" duties-droplist-list">
                                    @{
                foreach (var item in Model.PossibleEquipment)
                {



                    @Html.Partial("UseEquipment", item)

                }
                                    }

                                </ul>
                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("All Equipment", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div>
                                @Html.CheckBoxFor(model => model.AllEquipment, new { @class = "checkbox" })
                                @Html.ValidationMessageFor(model => model.AllEquipment, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>*@

            <div class="form-group">
                @Html.Label("Rate", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3 clearfix">
                    <div class="input-group">


                        @Html.HiddenFor(model => model.Rate, new { @class = "form-control" }) <span class="input-group-addon">%</span> 
                    </div>

                    @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.Label("Customs Value", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CustomsValue, new SelectList(ViewBag.Customs),  new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomsValue, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Duties")
    </div>

</div>



@section Scripts {
@Scripts.Render("~/bundles/jquery")


    @Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
@Scripts.Render("~/Scripts/duties.js")
@Scripts.Render("~/Scripts/Thousands.js")


}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/Projects.cshtml
    @model IEnumerable<NVIDev.Models.Project>

@{
    ViewBag.Title = "Projects";
}
@section Submenu{
    @Html.Partial("_AdminNav")


}
<div class="ibox-title">
    <h2>Projects</h2>
    <p>      
     @Html.ActionLink("Create New", "Create", "Project",null, new { @class ="btn btn-primary" })


    </p>
</div>

<div class="ibox-content">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>

            <th>
                @Html.Display("Full Name")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Revision)
            </th>
            <th>Flagged</th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                   @Html.Action("GetFullname","Admin", new { id = item.CurrentUserID })
                </td>
                <td>
                    @item.Revision.ToString("0.##")
                </td>
                @{
    bool ready = false;
                }
                @{

    if (!string.IsNullOrWhiteSpace(item.PVModuleIDS) && item.Valid)
    {
        if (item.UpfrontXI > 0)
        {
            <td class="text-success">Reviewed</td>

        }

        else
        {
            <td class="text-warning">Needs Review</td>
        }

        ready = true;
    }

    else
    {
        <td class="text-danger">Not Ready</td>
    }

                }
                <td>
                    @{
                if(ready)
                {
                    <span>@Html.ActionLink("Input", "EditVars", "Admin", new { id = item.Id }, null) |</span>
                        <span>@Html.ActionLink("Review", "Review", "Admin", new { id = item.Id }, null) |</span>
                        @*<span>@Html.ActionLink("Shipping ", "TestOrders", "Admin", new { id = item.Id }, null) |</span>*@

                }

                else
                {
                    <span>Input |</span>
                        <span>Review |</span>
                }
                    }

                    @Html.ActionLink("Details", "Details", "Project", new { id = item.Id }, null)

                </td>
            </tr>
}

    </table>
</div>

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/UseEquipment.cshtml
@model NVIDev.Models.DutyItem
@using (Html.BeginCollectionItem("UseEquipment"))
{
    <li>

        <label>@Html.CheckBoxFor(model => model.UseMe) @Model.Name</label>
        @Html.HiddenFor(model => model.Name)
    </li>

}

SolarAfrica Platform/SovTech/NVIDev/Views/Admin/ViewExcel.cshtml
@{
    ViewBag.Title = "View Excel";
}

<h2>View Excel</h2>

@{
    foreach(string erR in ViewBag.Errors)
    {
    <h3>@erR</h3>

    }
}